create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  role text,
  company text,
  headline text,
  bio text,
  avatar_url text,
  cover_url text,
  presentation_url text,
  whatsapp_number text,
  whatsapp_message text,
  calendar_url text,
  email text,
  phone text,
  website text,
  linkedin_url text,
  instagram_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cards (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  card_code text unique not null,
  label text,
  campaign text,
  location text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  card_id uuid references public.cards(id) on delete set null,
  card_code text,
  session_id uuid not null,
  event_type text not null check (
    event_type in (
      'page_view',
      'presentation_click',
      'whatsapp_click',
      'contact_download',
      'calendar_click',
      'website_click',
      'social_click'
    )
  ),
  referrer text,
  user_agent text,
  device_type text,
  browser text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  ip_hash_source text,
  created_at timestamptz not null default now()
);

create index if not exists events_profile_created_at_idx
  on public.events(profile_id, created_at desc);

create index if not exists events_card_code_idx
  on public.events(card_code);

alter table public.profiles enable row level security;
alter table public.cards enable row level security;
alter table public.events enable row level security;

grant select, insert, update, delete on public.profiles to service_role;
grant select, insert, update, delete on public.cards to service_role;
grant select, insert, update, delete on public.events to service_role;
grant usage, select on sequence public.events_id_seq to service_role;

create policy "Public profiles are readable"
  on public.profiles for select
  using (is_active = true);

create policy "Active cards are readable"
  on public.cards for select
  using (is_active = true);

-- Events are written only by the server with the service role.
-- Admin write policies should be added together with Supabase Auth in phase 3.
